[2023-12-03T20:46:41.403+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_local_to_gcs_python.upload_files_to_gcs manual__2023-12-03T20:46:37.865470+00:00 [queued]>
[2023-12-03T20:46:41.421+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_local_to_gcs_python.upload_files_to_gcs manual__2023-12-03T20:46:37.865470+00:00 [queued]>
[2023-12-03T20:46:41.422+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-03T20:46:41.439+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): upload_files_to_gcs> on 2023-12-03 20:46:37.865470+00:00
[2023-12-03T20:46:41.499+0000] {standard_task_runner.py:57} INFO - Started process 205 to run task
[2023-12-03T20:46:41.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'upload_local_to_gcs_python', 'upload_files_to_gcs', 'manual__2023-12-03T20:46:37.865470+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/local_to_GCS.py', '--cfg-path', '/tmp/tmp0i53sdjb']
[2023-12-03T20:46:41.529+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask upload_files_to_gcs
[2023-12-03T20:46:41.682+0000] {task_command.py:416} INFO - Running <TaskInstance: upload_local_to_gcs_python.upload_files_to_gcs manual__2023-12-03T20:46:37.865470+00:00 [running]> on host a00adb6852c7
[2023-12-03T20:46:42.004+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_owner' AIRFLOW_CTX_DAG_ID='upload_local_to_gcs_python' AIRFLOW_CTX_TASK_ID='upload_files_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T20:46:37.865470+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T20:46:37.865470+00:00'
[2023-12-03T20:46:42.010+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-03T20:46:42.012+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/Users/phunghongquan/google-cloud-sdk/bin gsutil cp /Users/phunghongquan/Documents/học kì 5/DataWarehouse/northwind_gitRepo/northwind_gitRepo/tables/Customers.csv gs://us-central1-test-env-b4f32c38-bucket/data']
[2023-12-03T20:46:42.037+0000] {subprocess.py:86} INFO - Output:
[2023-12-03T20:46:42.048+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /Users/phunghongquan/google-cloud-sdk/bin: No such file or directory
[2023-12-03T20:46:42.049+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-03T20:46:42.064+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-03T20:46:42.069+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_local_to_gcs_python, task_id=upload_files_to_gcs, execution_date=20231203T204637, start_date=20231203T204641, end_date=20231203T204642
[2023-12-03T20:46:42.088+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task upload_files_to_gcs (Bash command failed. The command returned a non-zero exit code 127.; 205)
[2023-12-03T20:46:42.120+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T20:46:42.153+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
