[2023-12-09T18:06:20.224+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow.load_to_bigquery manual__2023-12-09T18:06:07.020889+00:00 [queued]>
[2023-12-09T18:06:20.232+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow.load_to_bigquery manual__2023-12-09T18:06:07.020889+00:00 [queued]>
[2023-12-09T18:06:20.232+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T18:06:20.242+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bigquery> on 2023-12-09 18:06:07.020889+00:00
[2023-12-09T18:06:20.273+0000] {standard_task_runner.py:57} INFO - Started process 29735 to run task
[2023-12-09T18:06:20.278+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow', 'load_to_bigquery', 'manual__2023-12-09T18:06:07.020889+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/test_decorator.py', '--cfg-path', '/tmp/tmpvgvf9kkl']
[2023-12-09T18:06:20.282+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask load_to_bigquery
[2023-12-09T18:06:20.326+0000] {task_command.py:416} INFO - Running <TaskInstance: taskflow.load_to_bigquery manual__2023-12-09T18:06:07.020889+00:00 [running]> on host 3de6e37e1218
[2023-12-09T18:06:20.387+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='taskflow' AIRFLOW_CTX_TASK_ID='load_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T18:06:07.020889+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T18:06:07.020889+00:00'
[2023-12-09T18:06:20.397+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-09T18:06:20.398+0000] {base.py:73} INFO - Using connection ID 'google_cloud_datastore_default' for task execution.
[2023-12-09T18:06:20.399+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2023-12-09T18:06:20.400+0000] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2023-12-09T18:06:20.468+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 377, in execute
    self.configuration = self._use_existing_table()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 576, in _use_existing_table
    destination_project_id, destination_dataset, destination_table = self.hook.split_tablename(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2264, in split_tablename
    raise ValueError(f"Expected table name in the format of <dataset>.<table>. Got: {table_input}")
ValueError: Expected table name in the format of <dataset>.<table>. Got: f'{BQ_DATASET}
[2023-12-09T18:06:20.479+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=taskflow, task_id=load_to_bigquery, execution_date=20231209T180607, start_date=20231209T180620, end_date=20231209T180620
[2023-12-09T18:06:20.488+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 103 for task load_to_bigquery (Expected table name in the format of <dataset>.<table>. Got: f'{BQ_DATASET}; 29735)
[2023-12-09T18:06:20.500+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T18:06:20.514+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
