[2023-12-09T18:02:47.429+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow.load_to_bigquery manual__2023-12-09T18:02:31.278634+00:00 [queued]>
[2023-12-09T18:02:47.441+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow.load_to_bigquery manual__2023-12-09T18:02:31.278634+00:00 [queued]>
[2023-12-09T18:02:47.441+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T18:02:47.459+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bigquery> on 2023-12-09 18:02:31.278634+00:00
[2023-12-09T18:02:47.485+0000] {standard_task_runner.py:57} INFO - Started process 29537 to run task
[2023-12-09T18:02:47.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow', 'load_to_bigquery', 'manual__2023-12-09T18:02:31.278634+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/test_decorator.py', '--cfg-path', '/tmp/tmpnwtavh4s']
[2023-12-09T18:02:47.497+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask load_to_bigquery
[2023-12-09T18:02:47.563+0000] {task_command.py:416} INFO - Running <TaskInstance: taskflow.load_to_bigquery manual__2023-12-09T18:02:31.278634+00:00 [running]> on host 3de6e37e1218
[2023-12-09T18:02:47.645+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'load_to_bigquery', field 'destination_project_dataset_table'. Template: "{{ task_instance.xcom_pull(task_ids='upload_to_gcs')[0] }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-12-09T18:02:47.651+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-12-09T18:02:47.665+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=taskflow, task_id=load_to_bigquery, execution_date=20231209T180231, start_date=20231209T180247, end_date=20231209T180247
[2023-12-09T18:02:47.676+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 100 for task load_to_bigquery (None has no element 0; 29537)
[2023-12-09T18:02:47.705+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T18:02:47.721+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
