[2023-12-06T16:12:55.916+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test-dag.upload_files_to_gcs manual__2023-12-06T16:12:52.873776+00:00 [queued]>
[2023-12-06T16:12:55.923+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test-dag.upload_files_to_gcs manual__2023-12-06T16:12:52.873776+00:00 [queued]>
[2023-12-06T16:12:55.923+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2023-12-06T16:12:55.934+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): upload_files_to_gcs> on 2023-12-06 16:12:52.873776+00:00
[2023-12-06T16:12:55.950+0000] {standard_task_runner.py:57} INFO - Started process 725 to run task
[2023-12-06T16:12:55.987+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test-dag', 'upload_files_to_gcs', 'manual__2023-12-06T16:12:52.873776+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_BQ.py', '--cfg-path', '/tmp/tmpk0ttqlke']
[2023-12-06T16:12:56.017+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask upload_files_to_gcs
[2023-12-06T16:12:56.240+0000] {task_command.py:416} INFO - Running <TaskInstance: test-dag.upload_files_to_gcs manual__2023-12-06T16:12:52.873776+00:00 [running]> on host 7bb3453ab865
[2023-12-06T16:12:56.515+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phungquan' AIRFLOW_CTX_DAG_ID='test-dag' AIRFLOW_CTX_TASK_ID='upload_files_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2023-12-06T16:12:52.873776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-06T16:12:52.873776+00:00'
[2023-12-06T16:12:56.523+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-06T16:12:56.524+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gsutil -cp /Users/phunghongquan/Documents/học-kì-5/DataWarehouse/northwind_gitRepo/northwind_gitRepo/tables/Customers.csv gs://us-central1-test-env-b4f32c38-bucket/data']
[2023-12-06T16:12:56.566+0000] {subprocess.py:86} INFO - Output:
[2023-12-06T16:12:56.575+0000] {subprocess.py:93} INFO - /bin/bash: line 1: gsutil: command not found
[2023-12-06T16:12:56.576+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-06T16:12:56.610+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-06T16:12:56.622+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test-dag, task_id=upload_files_to_gcs, execution_date=20231206T161252, start_date=20231206T161255, end_date=20231206T161256
[2023-12-06T16:12:56.651+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task upload_files_to_gcs (Bash command failed. The command returned a non-zero exit code 127.; 725)
[2023-12-06T16:12:56.688+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-06T16:12:56.719+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
