[2023-12-08T02:44:33.048+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_local_to_gcs_python.upload_files_to_gcs manual__2023-12-08T02:44:29.917128+00:00 [queued]>
[2023-12-08T02:44:33.055+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_local_to_gcs_python.upload_files_to_gcs manual__2023-12-08T02:44:29.917128+00:00 [queued]>
[2023-12-08T02:44:33.055+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2023-12-08T02:44:33.066+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): upload_files_to_gcs> on 2023-12-08 02:44:29.917128+00:00
[2023-12-08T02:44:33.080+0000] {standard_task_runner.py:57} INFO - Started process 9251 to run task
[2023-12-08T02:44:33.088+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'upload_local_to_gcs_python', 'upload_files_to_gcs', 'manual__2023-12-08T02:44:29.917128+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/local_to_GCS.py', '--cfg-path', '/tmp/tmpq7k6g7se']
[2023-12-08T02:44:33.099+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask upload_files_to_gcs
[2023-12-08T02:44:33.175+0000] {task_command.py:416} INFO - Running <TaskInstance: upload_local_to_gcs_python.upload_files_to_gcs manual__2023-12-08T02:44:29.917128+00:00 [running]> on host 3de6e37e1218
[2023-12-08T02:44:33.255+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_owner' AIRFLOW_CTX_DAG_ID='upload_local_to_gcs_python' AIRFLOW_CTX_TASK_ID='upload_files_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T02:44:29.917128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-08T02:44:29.917128+00:00'
[2023-12-08T02:44:33.260+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-08T02:44:33.263+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gsutil -cp /opt/***/data/northwind_gitRepo/northwind_gitRepo/tables/Customers.csv gs://us-central1-test-env-b4f32c38-bucket']
[2023-12-08T02:44:33.284+0000] {subprocess.py:86} INFO - Output:
[2023-12-08T02:44:33.301+0000] {subprocess.py:93} INFO - /bin/bash: line 1: gsutil: command not found
[2023-12-08T02:44:33.301+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-08T02:44:33.316+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-08T02:44:33.319+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=upload_local_to_gcs_python, task_id=upload_files_to_gcs, execution_date=20231208T024429, start_date=20231208T024433, end_date=20231208T024433
[2023-12-08T02:44:33.331+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task upload_files_to_gcs (Bash command failed. The command returned a non-zero exit code 127.; 9251)
[2023-12-08T02:44:33.354+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-08T02:44:33.371+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
